language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: Pkl8O7Vj8NjxRnrN11Ncqq2RClkBMkKSITYIaBZEpZczUAPvzhDHEpgYS+2LLsYU4ZKl+laQ2QY/5HHANxBTCK2wV48o7ivhQZJn2Q6toru2gzw9QMVEKdvc0rgV2U8glT1kdvi6w0pt0WhRR8Fegp3ETsAWVDGIYbIx0R9B+B7F/cOtD2TD5LhOAd5BUrxt++EYPtv+j4L3azF8B1bGYxi2VsAVcFnokfZEDHSglImObDpS1xY1b8Eoo26muhyUvZM4MV9DaxR5SZ9tx8xUvnr2llTKkFD5spr2T88dL7rWbx0IRkX2Gp4O/HRJpaPnLISa202G8WP64MXspE6+KJVrjor+XGkaknVzLXIUoASwHT7UjLEphw+wGP/7xgtuaL/n3ZivPvyrTd2zdzx+lCMGDabE0MQxe9csmpVya/3W90R95Hi/qAOrtwbQaNlvrdRY2QO8xnfbcUIuxR8gRffQQZnX4UQTOg7Ln3VCTdWztrPesFEvUHhYmO/GLYTfDNv6NcdY5jwRXq7iLeo1XV7Xcoq9JT4mK+M3n7BaW2thaTRb/KAiATwSzQcTAZiIHGDfjdVnOv0H2NwNOUUZxnwaf9l0OoHmoZhlQskYWrp1uG+u6Gerz1i5Nzjpfaq9JsMpyK6TQX2oC4hS5J4KVBZ2C0MeegSlXkPw+FCmUJE=
  - secure: Uwf9gccsCo/DkpHFb+WnevIOc5pGw7EMEfjKQc2i2mmSWJxB3Kp5cUlcVk29zDzWr3VIH/EZVxgHVv4Z4AOMWU7gUr27QdC6vQf290zCka4A/kNEuploklBR5c/pUJtfBzIQh9MzEfr9w7jAbe2guIisxkHPq/dBZ3tW6OLB683hU1yUO0Ye6F/hqnxe5M4TNtb0g9gIpXCq//UghtJG3VAH7QuWHU4fAJeYfN9XVrJCV9Zv8MT6Rcu/14NVETwrGCfgzkBOakRFwK44Jlag6p1EWXo0Pn82bKvIOPU8uVtU3q21gHKtl/YMqBxbtbMiCKd+J2HqWnx17bQ+V5YtIj6ujN+ikT1zMr4GHB0+poK7z28LQScfuEM+Ye79khQOD0rGVC5pq/0onSY+s/Ao4p9aRpGAYK8k8AgYbPnmXFhCFm/1X0c/PjzJdmtnITLZJQYk0vytXVNXjzgpt0XrbpIPY5WIw8b19Fv1dZfIual+ig/r9Q9EO1FvcqHq6CDa1RF7ecfcRkZL4XWj003NMmXDxXV0uO7eWzENOb9Fb48Up5nXsQf7yzosuYH2yaau9GTUbUxjhAfXzsEERp1VIi5Phrf22H3FMsNMMlRHDaDMv8CFvjZmZ7BJRAsfOdO0wLq5xZeMsu7rG8WnpiY9Yazkv+9gzFrk2PXz8F/GIi8=
  - secure: StOYu6NNe2zr+k58KojkytpPlLwaWWy1hnztnYcCeWF/vp/OFHVrUKqnrX186ifwNEvrUJpUMhTB8kLsFYjwstmINh+Zxz5OPVYpzM35CBjbri2aBXs+kBUhuoTNygFXB0ZtfqvAzCXfWw2RBFzF4pGw5j1DFzj9SgietqeMOu34HBJplE8UtDPoUW7Xm7kObAEq7BY6sC9W+mKCPJ+cchbu6IsXua9LkV4bI8+Jb0V5OyNsPW8Ut6Bu+TTdaD19DqyP0ZrO8i3sZu7gLL4ezl0xXjVvWjGfxFMR6gRqPFZbuwPd6ROSflqwhXGhr8byRK5nvqBJG44J1kmEU5X+x+WdXNIWOobjUaDaieDYlKP20moDN/8zLuXLWsMH9rQ4WeCG9UXngqMuelY8czpubQZOU5zZntaR3VXvOqWOrtRZtI+cC5k6ZKJN9mjXxlt0k0B7yIPKa9k5GsgDnpsxZLDufOH9X6E9GEV65iRLx6n71J1lG6pMYPoN0Xy0w0O7KUYcV3+qHrU1snFBmTOnkmCss/1bJ2nzpo1o5uVkPiavBqK43zHPugeReTxEQ/gB3Lw9KWGBzmz02efp+D9B1Y2w2NAfuBU0ALVU51oYeyiAMVeYtHpvEQeP7q9+EJQiNKkI5r22nMgSZXYWEt7wfEs24cpRg0ZPCbnkNfBFpbE=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
